export interface Quote {
  text: string
  author?: string
  language: 'ar' | 'en'
}

export const QUOTES: Quote[] = [
  // Arabic Quotes (70)
  { text: "التعليم هو السلاح الأكثر قوة الذي يمكنك استخدامه لتغيير العالم", author: "نيلسون مانديلا", language: "ar" },
  { text: "النجاح لا يعني عدم السقوط، بل يعني النهوض في كل مرة نسقط فيها", author: "كونفوشيوس", language: "ar" },
  { text: "العقول العظيمة تناقش الأفكار، والعقول المتوسطة تناقش الأحداث، والعقول الصغيرة تناقش الأشخاص", author: "إليانور روزفلت", language: "ar" },
  { text: "أعظم مجد في الحياة ليس في عدم السقوط أبداً، بل في النهوض في كل مرة نسقط فيها", author: "نيلسون مانديلا", language: "ar" },
  { text: "الطريقة الوحيدة للقيام بعمل عظيم هي أن تحب ما تفعله", author: "ستيف جوبز", language: "ar" },
  { text: "المستقبل ينتمي لأولئك الذين يؤمنون بجمال أحلامهم", author: "إليانور روزفلت", language: "ar" },
  { text: "التعلم لا يُتعب العقل أبداً", author: "ليوناردو دا فينشي", language: "ar" },
  { text: "الاستثمار في المعرفة يحقق أفضل عائد", author: "بنجامين فرانكلين", language: "ar" },
  { text: "كل خبير كان مبتدئاً في يوم من الأيام", author: "هيلين هايز", language: "ar" },
  { text: "لا تنتظر الفرصة، بل اصنعها", author: "جورج برنارد شو", language: "ar" },
  { text: "في أحلك لحظاتنا يجب أن نركز لنرى النور", author: "أرسطو", language: "ar" },
  { text: "الشخص الوحيد المقدر لك أن تصبحه هو الشخص الذي تقرر أن تكونه", author: "رالف والدو إمرسون", language: "ar" },
  { text: "الأبطال يواصلون اللعب حتى يتقنوه", author: "بيلي جين كينغ", language: "ar" },
  { text: "الفرق بين العادي والاستثنائي هو ذلك القليل الإضافي", author: "جيمي جونسون", language: "ar" },
  { text: "لست كبيراً في السن أبداً لوضع هدف جديد أو لحلم جديد", author: "سي إس لويس", language: "ar" },
  { text: "الحد الوحيد لتحقيق الغد سيكون شكوكنا اليوم", author: "فرانكلين روزفلت", language: "ar" },
  { text: "لا تدع الأمس يأخذ مساحة كبيرة من اليوم", author: "ويل روجرز", language: "ar" },
  { text: "أفضل وقت لزراعة شجرة كان قبل 20 عاماً. ثاني أفضل وقت هو الآن", author: "المثل الصيني", language: "ar" },
  { text: "سواء كنت تعتقد أنك تستطيع أو لا تستطيع، فأنت محق", author: "هنري فورد", language: "ar" },
  { text: "المستقبل ينتمي لأولئك الذين يستعدون له اليوم", author: "مالكولم إكس", language: "ar" },
  { text: "تفوت 100% من الفرص التي لا تحاولها", author: "واين جريتزكي", language: "ar" },
  { text: "لم أفشل. لقد وجدت فقط 10000 طريقة لا تعمل", author: "توماس إديسون", language: "ar" },
  { text: "الشخص الذي لم يرتكب خطأ أبداً لم يجرب شيئاً جديداً أبداً", author: "ألبرت آينشتاين", language: "ar" },
  { text: "سر التقدم هو البداية", author: "مارك توين", language: "ar" },
  { text: "لا تخف من التخلي عن الجيد للحصول على العظيم", author: "جون روكفلر", language: "ar" },
  { text: "إذا لم تكن مستعداً للمخاطرة بالعادي، فسيتعين عليك الرضا بالعادي", author: "جيم رون", language: "ar" },
  { text: "جميع أحلامنا يمكن أن تتحقق إذا كان لدينا الشجاعة لمطاردتها", author: "والت ديزني", language: "ar" },
  { text: "النجاح هو أن تحب نفسك، وتحب ما تفعله، وتحب الطريقة التي تفعل بها ذلك", author: "مايا أنجيلو", language: "ar" },
  { text: "لا يجب أن تكون عظيماً لتبدأ، لكن يجب أن تبدأ لتكون عظيماً", author: "ليس براون", language: "ar" },
  { text: "بعد عام من الآن قد تتمنى لو أنك بدأت اليوم", author: "كارين لامب", language: "ar" },
  { text: "إذا كنت تستطيع حلم ذلك، يمكنك تحقيقه", author: "زيج زيجلار", language: "ar" },
  { text: "الأشياء العظيمة لا تأتي أبداً من مناطق الراحة", author: "مجهول", language: "ar" },
  { text: "احلم به. تمناه. افعله", author: "مجهول", language: "ar" },
  { text: "النجاح لا يجدك فقط. عليك أن تخرج وتحصل عليه", author: "مجهول", language: "ar" },
  { text: "كلما عملت بجد أكثر لشيء ما، كلما شعرت بعظمة أكبر عندما تحققه", author: "مجهول", language: "ar" },
  { text: "احلم أكبر. افعل أكبر", author: "مجهول", language: "ar" },
  { text: "لا تتوقف عندما تكون متعباً. توقف عندما تنتهي", author: "ويسلي سنايبس", language: "ar" },
  { text: "استيقظ بعزيمة. اذهب للنوم بارتياح", author: "مجهول", language: "ar" },
  { text: "افعل شيئاً اليوم سيشكرك عليه ذاتك المستقبلية", author: "شون فلانري", language: "ar" },
  { text: "الأشياء الصغيرة تصنع أياماً كبيرة", author: "مجهول", language: "ar" },
  { text: "سيكون صعباً، لكن الصعب لا يعني المستحيل", author: "مجهول", language: "ar" },
  { text: "أحياناً نُختبر ليس لإظهار نقاط ضعفنا، بل لاكتشاف نقاط قوتنا", author: "مجهول", language: "ar" },
  { text: "مفتاح النجاح هو التركيز على الأهداف، وليس العقبات", author: "مجهول", language: "ar" },
  { text: "احلم به. آمن به. ابنه", author: "مجهول", language: "ar" },
  { text: "قيودك - إنها مجرد خيالك", author: "مجهول", language: "ar" },
  { text: "ادفع نفسك، لأن لا أحد آخر سيفعل ذلك من أجلك", author: "مجهول", language: "ar" },
  { text: "التعليم ليس التحضير للحياة؛ التعليم هو الحياة نفسها", author: "جون ديوي", language: "ar" },
  { text: "إن مع العسر يسراً", author: "القرآن الكريم", language: "ar" },
  { text: "خير الناس أنفعهم للناس", author: "حديث شريف", language: "ar" },
  { text: "من تواضع لله رفعه", author: "حديث شريف", language: "ar" },
  { text: "الرفق ما كان في شيء إلا زانه", author: "حديث شريف", language: "ar" },
  { text: "من لم يشكر الناس لم يشكر الله", author: "حديث شريف", language: "ar" },
  { text: "أفضل الجهاد جهاد النفس", author: "حديث شريف", language: "ar" },
  { text: "الحكمة ضالة المؤمن", author: "حديث شريف", language: "ar" },
  { text: "طالب العلم يستغفر له كل شيء", author: "حديث شريف", language: "ar" },
  { text: "العلم خير من المال لأن العلم يحرسك وأنت تحرس المال", author: "علي بن أبي طالب", language: "ar" },
  { text: "من عرف نفسه فقد عرف ربه", author: "حديث شريف", language: "ar" },
  { text: "الظلم ظلمات يوم القيامة", author: "حديث شريف", language: "ar" },
  { text: "إياك والغضب فإنه يفسد الإيمان", author: "حديث شريف", language: "ar" },
  { text: "الكلمة الطيبة صدقة", author: "حديث شريف", language: "ar" },
  { text: "من سلك طريقاً يلتمس فيه علماً سهل الله له طريقاً إلى الجنة", author: "حديث شريف", language: "ar" },
  { text: "العلماء ورثة الأنبياء", author: "حديث شريف", language: "ar" },
  { text: "المؤمن القوي خير وأحب إلى الله من المؤمن الضعيف", author: "حديث شريف", language: "ar" },
  { text: "احرص على ما ينفعك واستعن بالله ولا تعجز", author: "حديث شريف", language: "ar" },
  { text: "إنما الأعمال بالنيات", author: "حديث شريف", language: "ar" },
  { text: "من كان في حاجة أخيه كان الله في حاجته", author: "حديث شريف", language: "ar" },
  { text: "تبسمك في وجه أخيك صدقة", author: "حديث شريف", language: "ar" },
  { text: "من أحب لقاء الله أحب الله لقاءه", author: "حديث شريف", language: "ar" },
  { text: "اعمل لدنياك كأنك تعيش أبداً واعمل لآخرتك كأنك تموت غداً", author: "علي بن أبي طالب", language: "ar" },
  { text: "لا تحقرن من المعروف شيئاً ولو أن تلقى أخاك بوجه طلق", author: "حديث شريف", language: "ar" },
  { text: "من يرد الله به خيراً يفقهه في الدين", author: "حديث شريف", language: "ar" },

  // English Quotes (70)
  { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela", language: "en" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", language: "en" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", language: "en" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins", language: "en" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", language: "en" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair", language: "en" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", language: "en" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", language: "en" },
  { text: "Learning never exhausts the mind.", author: "Leonardo da Vinci", language: "en" },
  { text: "The beautiful thing about learning is that no one can take it away from you.", author: "B.B. King", language: "en" },
  { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin", language: "en" },
  { text: "The expert in anything was once a beginner.", author: "Helen Hayes", language: "en" },
  { text: "Don't wait for opportunity. Create it.", author: "George Bernard Shaw", language: "en" },
  { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill", language: "en" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt", language: "en" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle", language: "en" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson", language: "en" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson", language: "en" },
  { text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau", language: "en" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King", language: "en" },
  { text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson", language: "en" },
  { text: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett", language: "en" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis", language: "en" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt", language: "en" },
  { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett", language: "en" },
  { text: "Don't let yesterday take up too much of today.", author: "Will Rogers", language: "en" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb", language: "en" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford", language: "en" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins", language: "en" },
  { text: "Life is what happens to you while you're busy making other plans.", author: "John Lennon", language: "en" },
  { text: "The future belongs to those who prepare for it today.", author: "Malcolm X", language: "en" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky", language: "en" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas A. Edison", language: "en" },
  { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein", language: "en" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", language: "en" },
  { text: "If you really look closely, most overnight successes took a long time.", author: "Steve Jobs", language: "en" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain", language: "en" },
  { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller", language: "en" },
  { text: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn", language: "en" },
  { text: "Take up one idea. Make that one idea your life. Think of it, dream of it, live on that idea.", author: "Swami Vivekananda", language: "en" },
  { text: "All our dreams can come true if we have the courage to pursue them.", author: "Walt Disney", language: "en" },
  { text: "Good things come to people who wait, but better things come to those who go out and get them.", author: "Anonymous", language: "en" },
  { text: "If you do what you always did, you will get what you always got.", author: "Anonymous", language: "en" },
  { text: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou", language: "en" },
  { text: "You don't have to be great to get started, but you have to get started to be great.", author: "Les Brown", language: "en" },
  { text: "A year from now you may wish you had started today.", author: "Karen Lamb", language: "en" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", language: "en" },
  { text: "If you can dream it, you can achieve it.", author: "Zig Ziglar", language: "en" },
  { text: "Great things never come from comfort zones.", author: "Anonymous", language: "en" },
  { text: "Dream it. Wish it. Do it.", author: "Anonymous", language: "en" },
  { text: "Success doesn't just find you. You have to go out and get it.", author: "Anonymous", language: "en" },
  { text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Anonymous", language: "en" },
  { text: "Dream bigger. Do bigger.", author: "Anonymous", language: "en" },
  { text: "Don't stop when you're tired. Stop when you're done.", author: "Wesley Snipes", language: "en" },
  { text: "Wake up with determination. Go to bed with satisfaction.", author: "Anonymous", language: "en" },
  { text: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery", language: "en" },
  { text: "Little things make big days.", author: "Anonymous", language: "en" },
  { text: "It's going to be hard, but hard does not mean impossible.", author: "Anonymous", language: "en" },
  { text: "Don't wait for opportunity. Create it.", author: "Anonymous", language: "en" },
  { text: "Sometimes we're tested not to show our weaknesses, but to discover our strengths.", author: "Anonymous", language: "en" },
  { text: "The key to success is to focus on goals, not obstacles.", author: "Anonymous", language: "en" },
  { text: "Dream it. Believe it. Build it.", author: "Anonymous", language: "en" },
  { text: "Your limitation—it's only your imagination.", author: "Anonymous", language: "en" },
  { text: "Push yourself, because no one else is going to do it for you.", author: "Anonymous", language: "en" },
  { text: "Great things never come from comfort zones.", author: "Anonymous", language: "en" },
  { text: "Dream it. Wish it. Do it.", author: "Anonymous", language: "en" },
  { text: "Success doesn't just find you. You have to go out and get it.", author: "Anonymous", language: "en" },
  { text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Anonymous", language: "en" },
  { text: "Dream bigger. Do bigger.", author: "Anonymous", language: "en" },
  { text: "Don't stop when you're tired. Stop when you're done.", author: "Anonymous", language: "en" },
  { text: "Wake up with determination. Go to bed with satisfaction.", author: "Anonymous", language: "en" },
  { text: "Do something today that your future self will thank you for.", author: "Anonymous", language: "en" },
  { text: "Education is not preparation for life; education is life itself.", author: "John Dewey", language: "en" }
]

export function getRandomQuote(): Quote {
  return QUOTES[Math.floor(Math.random() * QUOTES.length)]
}