export interface Quote {
  text: string
  author?: string
  language: 'ar' | 'en'
}

export const QUOTES: Quote[] = [
  // Arabic Quotes (70)
  { text: "العلم نور والجهل ظلام", author: "مثل عربي", language: "ar" },
  { text: "من طلب العلا سهر الليالي", author: "مثل عربي", language: "ar" },
  { text: "اطلبوا العلم من المهد إلى اللحد", author: "مثل عربي", language: "ar" },
  { text: "العلم في الصغر كالنقش على الحجر", author: "مثل عربي", language: "ar" },
  { text: "من جد وجد ومن زرع حصد", author: "مثل عربي", language: "ar" },
  { text: "لا تؤجل عمل اليوم إلى الغد", author: "مثل عربي", language: "ar" },
  { text: "الصبر مفتاح الفرج", author: "مثل عربي", language: "ar" },
  { text: "من لم يتعلم في الصغر لم يتقدم في الكبر", author: "مثل عربي", language: "ar" },
  { text: "العلم خير من المال لأن العلم يحرسك وأنت تحرس المال", author: "علي بن أبي طالب", language: "ar" },
  { text: "تعلموا فإن العلم زينة في الرخاء وعدة في البلاء", author: "مثل عربي", language: "ar" },
  { text: "الدنيا ساعة فاجعلها طاعة", author: "مثل عربي", language: "ar" },
  { text: "من عمل بما علم أورثه الله علم ما لم يعلم", author: "مثل عربي", language: "ar" },
  { text: "أول العلم الصمت والثاني الاستماع والثالث الحفظ والرابع العمل والخامس النشر", author: "مثل عربي", language: "ar" },
  { text: "إذا لم تكن عالماً فكن طالب علم", author: "مثل عربي", language: "ar" },
  { text: "من سار على الدرب وصل", author: "مثل عربي", language: "ar" },
  { text: "الجهل عدو نفسه فكيف يكون صديق غيره", author: "مثل عربي", language: "ar" },
  { text: "أطلب العلم ولو في الصين", author: "حديث شريف", language: "ar" },
  { text: "التكرار يعلم الحمار", author: "مثل عربي", language: "ar" },
  { text: "من تعلم صغيراً انتفع كبيراً", author: "مثل عربي", language: "ar" },
  { text: "العقل زينة والجهل شين", author: "مثل عربي", language: "ar" },
  { text: "من طلب شيئاً بجد وجد", author: "مثل عربي", language: "ar" },
  { text: "المعرفة قوة", author: "مثل عربي", language: "ar" },
  { text: "رب ضارة نافعة", author: "مثل عربي", language: "ar" },
  { text: "إن مع العسر يسراً", author: "قرآن كريم", language: "ar" },
  { text: "الحياة مدرسة والتجربة أستاذها", author: "مثل عربي", language: "ar" },
  { text: "من صبر ظفر", author: "مثل عربي", language: "ar" },
  { text: "الوقت كالسيف إن لم تقطعه قطعك", author: "مثل عربي", language: "ar" },
  { text: "آفة العلم النسيان", author: "مثل عربي", language: "ar" },
  { text: "من لم يذق مر التعلم ساعة تجرع ذل الجهل طوال حياته", author: "مثل عربي", language: "ar" },
  { text: "القراءة تصنع الإنسان الكامل", author: "مثل عربي", language: "ar" },
  { text: "التعليم في الصغر كالنقش في الحجر", author: "مثل عربي", language: "ar" },
  { text: "من أحب شيئاً أكثر من ذكره", author: "مثل عربي", language: "ar" },
  { text: "خير الناس أنفعهم للناس", author: "حديث شريف", language: "ar" },
  { text: "لا يضيع مع الله عمل", author: "مثل عربي", language: "ar" },
  { text: "البداية نصف الطريق", author: "مثل عربي", language: "ar" },
  { text: "من عاش بلا هدف مات بلا أثر", author: "مثل عربي", language: "ar" },
  { text: "الطموح بداية الطريق إلى النجاح", author: "مثل عربي", language: "ar" },
  { text: "المثابرة والعزيمة قوة لا تقهر", author: "مثل عربي", language: "ar" },
  { text: "النجاح لا يأتي إلا بالعمل والاجتهاد", author: "مثل عربي", language: "ar" },
  { text: "الهمة العالية تصنع المعجزات", author: "مثل عربي", language: "ar" },
  { text: "من أراد النجاح فليصبر على التعب", author: "مثل عربي", language: "ar" },
  { text: "الفشل بداية النجاح إذا تعلمنا منه", author: "مثل عربي", language: "ar" },
  { text: "التفوق يحتاج إلى تضحية", author: "مثل عربي", language: "ar" },
  { text: "الحلم بداية الحقيقة", author: "مثل عربي", language: "ar" },
  { text: "من لم يشكر الناس لم يشكر الله", author: "حديث شريف", language: "ar" },
  { text: "الاستمرار سر النجاح", author: "مثل عربي", language: "ar" },
  { text: "المعلم والطبيب لا ينصحان عدوا", author: "مثل عربي", language: "ar" },
  { text: "العلم أفضل من الذهب والفضة", author: "مثل عربي", language: "ar" },
  { text: "من تواضع لله رفعه", author: "حديث شريف", language: "ar" },
  { text: "الكتاب نعم الجليس والأنيس", author: "مثل عربي", language: "ar" },
  { text: "من عرف نفسه فقد عرف ربه", author: "حديث شريف", language: "ar" },
  { text: "الصدق منجاة والكذب مهلكة", author: "مثل عربي", language: "ar" },
  { text: "خذ الحكمة من أفواه المجانين", author: "مثل عربي", language: "ar" },
  { text: "من أعان ظالماً على ظلمه فقد ظلم نفسه", author: "مثل عربي", language: "ar" },
  { text: "الرفق ما كان في شيء إلا زانه", author: "حديث شريف", language: "ar" },
  { text: "من أحيا علماً أحيا الله قلبه", author: "مثل عربي", language: "ar" },
  { text: "أفضل الجهاد جهاد النفس", author: "حديث شريف", language: "ar" },
  { text: "من أراد الآخرة فليترك الدنيا", author: "مثل عربي", language: "ar" },
  { text: "صاحب الحق قوي ولو كان وحده", author: "مثل عربي", language: "ar" },
  { text: "الظلم ظلمات يوم القيامة", author: "حديث شريف", language: "ar" },
  { text: "من استشار الرجال شاركها عقولها", author: "مثل عربي", language: "ar" },
  { text: "إياك والغضب فإنه يفسد الإيمان", author: "حديث شريف", language: "ar" },
  { text: "من قل صدقه قل صديقه", author: "مثل عربي", language: "ar" },
  { text: "العمل بالعلم يثبته في القلب", author: "مثل عربي", language: "ar" },
  { text: "طالب العلم يستغفر له كل شيء", author: "حديث شريف", language: "ar" },
  { text: "من تعلم وعلم فذلك يدعى عظيماً", author: "مثل عربي", language: "ar" },
  { text: "أكرم الناس أنفعهم", author: "مثل عربي", language: "ar" },
  { text: "الحياة قصيرة والفن طويل", author: "مثل عربي", language: "ar" },
  { text: "من طلب المعالي لم ينم الليالي", author: "مثل عربي", language: "ar" },
  { text: "الحكمة ضالة المؤمن", author: "حديث شريف", language: "ar" },
  { text: "العادة طبيعة ثانية", author: "مثل عربي", language: "ar" },

  // English Quotes (70)
  { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela", language: "en" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", language: "en" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", language: "en" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins", language: "en" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", language: "en" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair", language: "en" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", language: "en" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", language: "en" },
  { text: "Learning never exhausts the mind.", author: "Leonardo da Vinci", language: "en" },
  { text: "The beautiful thing about learning is that no one can take it away from you.", author: "B.B. King", language: "en" },
  { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin", language: "en" },
  { text: "The expert in anything was once a beginner.", author: "Helen Hayes", language: "en" },
  { text: "Don't wait for opportunity. Create it.", author: "George Bernard Shaw", language: "en" },
  { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill", language: "en" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt", language: "en" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle", language: "en" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson", language: "en" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson", language: "en" },
  { text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau", language: "en" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King", language: "en" },
  { text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson", language: "en" },
  { text: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett", language: "en" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis", language: "en" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt", language: "en" },
  { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett", language: "en" },
  { text: "Don't let yesterday take up too much of today.", author: "Will Rogers", language: "en" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb", language: "en" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford", language: "en" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins", language: "en" },
  { text: "Life is what happens to you while you're busy making other plans.", author: "John Lennon", language: "en" },
  { text: "The future belongs to those who prepare for it today.", author: "Malcolm X", language: "en" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky", language: "en" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas A. Edison", language: "en" },
  { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein", language: "en" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", language: "en" },
  { text: "If you really look closely, most overnight successes took a long time.", author: "Steve Jobs", language: "en" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain", language: "en" },
  { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller", language: "en" },
  { text: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn", language: "en" },
  { text: "Take up one idea. Make that one idea your life. Think of it, dream of it, live on that idea.", author: "Swami Vivekananda", language: "en" },
  { text: "All our dreams can come true if we have the courage to pursue them.", author: "Walt Disney", language: "en" },
  { text: "Good things come to people who wait, but better things come to those who go out and get them.", author: "Anonymous", language: "en" },
  { text: "If you do what you always did, you will get what you always got.", author: "Anonymous", language: "en" },
  { text: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou", language: "en" },
  { text: "You don't have to be great to get started, but you have to get started to be great.", author: "Les Brown", language: "en" },
  { text: "A year from now you may wish you had started today.", author: "Karen Lamb", language: "en" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", language: "en" },
  { text: "If you can dream it, you can achieve it.", author: "Zig Ziglar", language: "en" },
  { text: "Great things never come from comfort zones.", author: "Anonymous", language: "en" },
  { text: "Dream it. Wish it. Do it.", author: "Anonymous", language: "en" },
  { text: "Success doesn't just find you. You have to go out and get it.", author: "Anonymous", language: "en" },
  { text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Anonymous", language: "en" },
  { text: "Dream bigger. Do bigger.", author: "Anonymous", language: "en" },
  { text: "Don't stop when you're tired. Stop when you're done.", author: "Wesley Snipes", language: "en" },
  { text: "Wake up with determination. Go to bed with satisfaction.", author: "Anonymous", language: "en" },
  { text: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery", language: "en" },
  { text: "Little things make big days.", author: "Anonymous", language: "en" },
  { text: "It's going to be hard, but hard does not mean impossible.", author: "Anonymous", language: "en" },
  { text: "Don't wait for opportunity. Create it.", author: "Anonymous", language: "en" },
  { text: "Sometimes we're tested not to show our weaknesses, but to discover our strengths.", author: "Anonymous", language: "en" },
  { text: "The key to success is to focus on goals, not obstacles.", author: "Anonymous", language: "en" },
  { text: "Dream it. Believe it. Build it.", author: "Anonymous", language: "en" },
  { text: "Your limitation—it's only your imagination.", author: "Anonymous", language: "en" },
  { text: "Push yourself, because no one else is going to do it for you.", author: "Anonymous", language: "en" },
  { text: "Great things never come from comfort zones.", author: "Anonymous", language: "en" },
  { text: "Dream it. Wish it. Do it.", author: "Anonymous", language: "en" },
  { text: "Success doesn't just find you. You have to go out and get it.", author: "Anonymous", language: "en" },
  { text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Anonymous", language: "en" },
  { text: "Dream bigger. Do bigger.", author: "Anonymous", language: "en" },
  { text: "Don't stop when you're tired. Stop when you're done.", author: "Anonymous", language: "en" },
  { text: "Wake up with determination. Go to bed with satisfaction.", author: "Anonymous", language: "en" },
  { text: "Do something today that your future self will thank you for.", author: "Anonymous", language: "en" },
  { text: "Education is not preparation for life; education is life itself.", author: "John Dewey", language: "en" }
]

export function getRandomQuote(): Quote {
  return QUOTES[Math.floor(Math.random() * QUOTES.length)]
}